CREATE TABLE IF NOT EXISTS airports (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

  ciad VARCHAR(6) NOT NULL UNIQUE CHECK (LENGTH(TRIM(ciad)) = 6),
  codigoOACI CHAR(4) NOT NULL UNIQUE CHECK (LENGTH(TRIM(codigoOACI)) = 4),
  airport_name VARCHAR(150) NOT NULL,
  state VARCHAR(50) NOT NULL,
  city VARCHAR(50) NOT NULL,
  altitude DOUBLE PRECISION NOT NULL,
  latgeopoint DOUBLE PRECISION NOT NULL,
  longeopoint DOUBLE PRECISION NOT NULL,
  latitude VARCHAR(25) NOT NULL,
  longitude VARCHAR(25) NOT NULL,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )